
# OUTPUT FILE
result_path : './results'
result_filename : AlexNet

# OUTPUT FILE PRINTING MODE
# 'concise' for printing the basic information for each optimal design point found, i.e. energy and performance.
# 'complete' for printing all detailed information for each optimal design point found for in-depth analysis.
result_print_mode : complete

# SEARCH SETTINGS
# 'False' for searching the corresponding space.
fixed_architecture : False
fixed_spatial_unrolling : False
fixed_temporal_mapping : False

# RESULT SAVING SETTINGS
# 'False' for only saving the best result.
# Be careful to put "save_all_temporal_mapping_result" to True, because it can generate large result files.
save_all_architecture_result : True
save_all_spatial_unrolling_result : True
save_all_temporal_mapping_result : False

# WORKLOAD
# layer_indices can be a single-element list or a multiple-element list.
layer_filename : './NN_layers/AlexNet'
layer_indices : [3,5]

# MULTIPROCESSING
# run the framework in multiprocessing mode to speedup the search procedure.
layer_multiprocessing : 100
architecture_search_multiprocessing : 100
spatial_unrolling_multiprocessing : 100
temporal_mapping_multiprocessing: 100

# TEMPORAL MAPPING GENERATOR SETTINGS
# search_method : exhaustive / heuristic_v1 / heuristic_v2
temporal_mapping_search_method : heuristic_v1

# SPATIAL MAPPING GENERATOR SETTINGS
# search method : exhaustive / heuristic_v1 / heuristic_v2 / hint_driven
# If 'hint_driven' is chosen, 'spatial_mapping_list' in the mapping file will be used.
spatial_unrolling_search_method : hint_driven
spatial_utilization_threshold : 0.9

