
# OUTPUT FILE
result_path : './results_FB_Oct/SU_fix'
#result_path : './test_multi_layer'
result_filename : FB

# OUTPUT FILE PRINTING MODE
# 'concise' for printing the basic information for each optimal design point found, i.e. energy and performance.
# 'complete' for printing all detailed information for each optimal design point found for in-depth analysis.
result_print_mode : complete

# SEARCH SETTINGS
# 'False' for searching the corresponding space.
fixed_architecture : True
fixed_spatial_unrolling : True
fixed_temporal_mapping : False

# RESULT SAVING SETTINGS
# 'False' for only saving the best result.
# Be careful to put they to True, because it can generate large result files.
save_all_architecture_result : True
save_all_spatial_unrolling_result : True
save_all_temporal_mapping_result : False

# WORKLOAD
# layer_indices can be a single-element list or a multiple-element list.
layer_filename : './NN_layers/FB'
layer_indices : [1]

# MULTIPROCESSING
# run the framework in multiprocessing mode to speedup the search procedure.
layer_multiprocessing : 100
architecture_search_multiprocessing : 100
spatial_unrolling_multiprocessing : 100

# TEMPORAL MAPPING GENERATOR SETTINGS
# search_method : exhaustive / heuristic_v1 / heuristic_v2 / iterative
temporal_mapping_search_method : exhaustive

# SPATIAL MAPPING GENERATOR SETTINGS
# search method : exhaustive / heuristic_v1 / heuristic_v2 / hint_driven / hint_driven_with_greedy_mapping
# If 'hint_driven' is chosen, 'spatial_mapping_list' in the mapping file will be used,
# and 'spatial_utilization_threshold' below will be ignored.
spatial_unrolling_search_method : hint_driven_with_greedy_mapping
spatial_utilization_threshold : 0.7