
# OUTPUT FILE
result_path : '.Steven/results2'
result_filename : Steven_Layers

# OUTPUT FILE PRINTING MODE
# 'concise' for printing the basic information for each optimal design point found, i.e. energy and performance.
# 'complete' for printing all detailed information for each optimal design point found for in-depth analysis.
result_print_mode : complete

# SEARCH SETTINGS
# 'False' for searching the corresponding space.
fixed_architecture : True
fixed_spatial_unrolling : True
fixed_temporal_mapping : False

# RESULT SAVING SETTINGS
# 'False' for only saving the best result.
# Be careful to put they to True, because it can generate large result files.
save_all_architecture_result : False
save_all_spatial_unrolling_result : False
save_all_temporal_mapping_result : False

# WORKLOAD
# layer_indices can be a single-element list or a multiple-element list.
layer_filename : './Steven/layers_of_interest1'
#layer_indices : [24001,24002,24003,24004,24005,24006,24007,24008,24009,24010,24011,24012,24013,24014,24015,24016,
#24017,24018,24019,24020,24021,24022,24023,24024,24025,24026,24027,24028,24029,24030,24031,24032,
#24033,24034,24035,24036,24037,24038,24039,24040,24041,24042,24043,24044,24045,24046,24047,24048,
#24049,24050,24051,24052,24053,24054,24055,24056,24057,24058,24059,24060,24061,24062,24063,24064,24065]
layer_indices : [22004]
# MULTIPROCESSING
# run the framework in multiprocessing mode to speedup the search procedure.
layer_multiprocessing : 1
architecture_search_multiprocessing : 1
spatial_unrolling_multiprocessing : 1
temporal_mapping_multiprocessing: 100

# TEMPORAL MAPPING GENERATOR SETTINGS
# search_method : exhaustive / heuristic_v1 / heuristic_v2 / iterative
temporal_mapping_search_method : exhaustive

# SPATIAL MAPPING GENERATOR SETTINGS
# search method : exhaustive / heuristic_v1 / heuristic_v2 / hint_driven / greedy_mapping_with_hint / greedy_mapping_without_hint
# If 'hint_driven' is chosen, 'spatial_mapping_list' in the mapping file will be used.
spatial_unrolling_search_method : greedy_mapping_with_hint
spatial_utilization_threshold : 0.9

# CONV im2col ENABLE
# Weight matrix [K,       C|FX|FY]
# Input  matrix [B|OY|OX, C|FY|FX]
# Output matrix [K,       B|OY|OX]
# For pointwise layers (FX=FY=1), recommend to put im2col_enable True.
im2col_enable : False

