
# OUTPUT FILE
result_path : './New_0p9'
result_filename : Eyeriss_Birds

# OUTPUT FILE PRINTING MODE
# 'concise' for printing the basic information for each optimal design point found, i.e. energy and performance.
# 'complete' for printing all detailed information for each optimal design point found for in-depth analysis.
result_print_mode : complete

# SEARCH SETTINGS
# 'False' for searching the corresponding space.
fixed_architecture : True
fixed_spatial_unrolling : True
fixed_temporal_mapping : False
# RESULT SAVING SETTINGS
# 'False' for only saving the best result.
# Be careful to put they to True, because it can generate large result files.
save_all_architecture_result : False
save_all_spatial_unrolling_result : False
save_all_temporal_mapping_result : False

# WORKLOAD
# layer_indices can be a single-element list or a multiple-element list.
# For now, please keep it as a single-element list.
layer_filename : './Steven2/layers_of_interest1'
#layer_indices :  [3002]
layer_indices :  [15032]
#layer_indices :  [10023]
#layer_indices :  [10035]
#layer_indices :  [10038]
#layer_indices :  [11020]
#layer_indices :  [11028]

# MULTIPROCESSING
# run the framework in multiprocessing mode to speedup the search procedure.
layer_multiprocessing : 1
architecture_search_multiprocessing : 1
spatial_unrolling_multiprocessing : 1
temporal_mapping_multiprocessing : 100

# TEMPORAL MAPPING GENERATOR SETTINGS
# search_method : exhaustive / heuristic_v1 / heuristic_v2 / iterative
temporal_mapping_search_method : exhaustive

# SPATIAL MAPPING GENERATOR SETTINGS
# search method : exhaustive / heuristic_v1 / heuristic_v2 / hint_driven
# If 'hint_driven' is chosen, 'spatial_mapping_list' in the mapping file will be used,
# and 'spatial_utilization_threshold' below will be ignored.
spatial_unrolling_search_method : greedy_mapping_with_hint
spatial_utilization_threshold : 0.9

# CONV im2col ENABLE
# Weight matrix [K,       C|FX|FY]
# Input  matrix [B|OY|OX, C|FY|FX]
# Output matrix [K,       B|OY|OX]
# For pointwise layers (FX=FY=1), recommend to put im2col_enable True.
im2col_enable : False
