
# OUTPUT FILE
result_path : './results_baseline_architecture_2'
result_filename : Eyeriss_Birds

# OUTPUT FILE PRINTING MODE
# 'concise' for printing the basic information for each optimal design point found, i.e. energy and performance.
# 'complete' for printing all detailed information for each optimal design point found for in-depth analysis.
result_print_mode : complete

# SEARCH SETTINGS
# 'False' for searching the corresponding space.
fixed_architecture : True
fixed_spatial_unrolling : True
fixed_temporal_mapping : False
# RESULT SAVING SETTINGS
# 'False' for only saving the best result.
# Be careful to put they to True, because it can generate large result files.
save_all_architecture_result : False
save_all_spatial_unrolling_result : False
save_all_temporal_mapping_result : False

# WORKLOAD
# layer_indices can be a single-element list or a multiple-element list.
# For now, please keep it as a single-element list.
layer_filename : './NN_layers/layers_of_interest1'
layer_indices :  [
4002,4003,4004,4005,4006,4007,4008,4009,4010,4011,4012,4013,4014,4015,4016,4017,4018,4019,4020,4021,4022,4023,4024,4025,4026,4027,4028,4029,4030,4031,4032,4033,4034,4035,4036,4037,4038,4039,4040,4041,4042,4043,4044,4045,4046,4047,4048,4049,4050,4051,4052,4053,4054,4055,4056,4057,4058,4059,4060,4061,4062,4063,4064,4065]
# MULTIPROCESSING
# run the framework in multiprocessing mode to speedup the search procedure.
layer_multiprocessing : 1
architecture_search_multiprocessing : 100
spatial_unrolling_multiprocessing : 100

# TEMPORAL MAPPING GENERATOR SETTINGS
# search_method : exhaustive / heuristic_v1 / heuristic_v2 / iterative
temporal_mapping_search_method : exhaustive

# SPATIAL MAPPING GENERATOR SETTINGS
# search method : exhaustive / heuristic_v1 / heuristic_v2 / hint_driven
# If 'hint_driven' is chosen, 'spatial_mapping_list' in the mapping file will be used,
# and 'spatial_utilization_threshold' below will be ignored.
spatial_unrolling_search_method : hint_driven
spatial_utilization_threshold : 0
