
# OUTPUT FILE
result_path : './results_baseline_architecture_2'
result_filename : Eyeriss_Birds

# OUTPUT FILE PRINTING MODE
# 'concise' for printing the basic information for each optimal design point found, i.e. energy and performance.
# 'complete' for printing all detailed information for each optimal design point found for in-depth analysis.
result_print_mode : complete

# SEARCH SETTINGS
# 'False' for searching the corresponding space.
fixed_architecture : True
fixed_spatial_unrolling : True
fixed_temporal_mapping : False
# RESULT SAVING SETTINGS
# 'False' for only saving the best result.
# Be careful to put they to True, because it can generate large result files.
save_all_architecture_result : False
save_all_spatial_unrolling_result : False
save_all_temporal_mapping_result : False

# WORKLOAD
# layer_indices can be a single-element list or a multiple-element list.
# For now, please keep it as a single-element list.
layer_filename : './NN_layers/layers_of_interest1'
layer_indices :  [
8002,8003,8004,8005,8006,8007,8008,8009,8010,8011,8012,8013,8014,8015,8016,8017,8018,8019,8020,8021,8022,8023,8024,8025,8026,8027,8028,8029,8030,8031,8032,8033,8034,8035,8036,8037,8038,8039,8040,8041,8042,8043,8044,8045,8046,8047,8048,8049]
# MULTIPROCESSING
# run the framework in multiprocessing mode to speedup the search procedure.
layer_multiprocessing : 1
architecture_search_multiprocessing : 100
spatial_unrolling_multiprocessing : 100

# TEMPORAL MAPPING GENERATOR SETTINGS
# search_method : exhaustive / heuristic_v1 / heuristic_v2 / iterative
temporal_mapping_search_method : exhaustive

# SPATIAL MAPPING GENERATOR SETTINGS
# search method : exhaustive / heuristic_v1 / heuristic_v2 / hint_driven
# If 'hint_driven' is chosen, 'spatial_mapping_list' in the mapping file will be used,
# and 'spatial_utilization_threshold' below will be ignored.
spatial_unrolling_search_method : hint_driven
spatial_utilization_threshold : 0
